  
blank_issues_enabled: false
contact_links:
  - name: YatopiaMC Discord
    url: https://discord.gg/yatopiamc
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!
